name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/node-docker-good-defaults:${{ github.run_number }}-${{ github.sha }}

    - name: docker login to registry
      run : docker login -u ${{ secrets.docker_hub_user }} -p ${{ secrets.docker_hub_pass }}

      
